[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fent = "FLp9vpfqWwoFA6RejXxZAWKmgfcb98TNFnLeAbZqk6QD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
