[toolchain]
anchor_version = "1.0.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fent = "6Kkk6nvLC4RombhmjQvRD77ZE1UKLoXMPBLup7gZN7ZR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
